language: node_js
node_js:
  - "0.11"
  - "0.10"

before_script:
  - gulp

script:
  - npm run-script coveralls

services:
  - redis-server

notifications:
  webhooks:
    urls:
      - http://78.91.0.217:3000/api/github
    on_success: always
    on_failure: never  
