export {
    TIMEOUT: process.env.CENSUS_TIMEOUT or 15 * 60 * 1000
    REMOVAL_TIMEOUT: process.env.CENSUS_REMOVAL_TIMEOUT or 7 * 24 * 60 * 60 * 1000
    ORG_USER: process.env.ORG_USER or 'abakus'
    PASSPORT_STRATEGY: process.env.PASSPORT_STRATEGY
    PASSPORT_STRATEGY_OPTIONS: process.env.PASSPORT_STRATEGY_OPTIONS or {}
    REDIS_HOST: process.env.REDIS_HOST or '127.0.0.1'
    REDIS_PORT: process.env.REDIS_PORT or 6379
    REDIS_PASSWORD: process.env.REDIS_PASSWORD
}
