import redis
export {
    client: () ->
        host = null
        password = process.env.REDIS_PASSWORD
        # istanbul ignore if
        if process.env.NODE_ENV == 'production'
            host = 'leia.abakus.no'
        else
            host = '127.0.0.1'

        client = redis.createClient(6379, host, {})

        # istanbul ignore if
        if password
            client.auth(password)
        return client
}
